// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dodirhrhuvrwnywgbida.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZGlyaHJodXZyd255d2diaWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTYyODMsImV4cCI6MjA2NjY5MjI4M30.gP_gf4LqGW2e1XFuwQSXzFRsGZKmNQyIXtg8NTNuB_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);