// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebztehkjmyqqaadqagmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVienRlaGtqbXlxcWFhZHFhZ21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTg3MjgsImV4cCI6MjA2NjY5NDcyOH0.2nNknD9pV4zhRf_E-FlPHMrFbI2KTsi2BKwpvIqOQUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);